services:
  - type: web
    name: duolingo-clone
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/v1/health
    autoDeployTrigger: commit
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: /api/v1
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
